import { NAMESPACE } from '../constants';

export const TOGGLE_ASSET_DETAILS = `${NAMESPACE}/asset/TOGGLE_ASSET_DETAILS`;
export const TOGGLE_ASSET_RECOMMENDATIONS = `${NAMESPACE}/asset/TOGGLE_ASSET_RECOMMENDATIONS`;
