import { NAMESPACE } from '../constants';

export const TOGGLE_OFFER_DETAILS = `${NAMESPACE}/offers/TOGGLE_OFFER_DETAILS`;
export const TOGGLE_OFFER_RECOMMENDATIONS = `${NAMESPACE}/offers/TOGGLE_OFFER_RECOMMENDATIONS`;
