import { NAMESPACE } from '../constants';

export const TOGGLE_REQUEST_DETAILS = `${NAMESPACE}/requests/TOGGLE_OFFER_DETAILS`;
export const TOGGLE_REQUEST_RECOMMENDATIONS = `${NAMESPACE}/requests/TOGGLE_REQUEST_RECOMMENDATIONS`;
